Lower max-connections to 90, keeping it below the built-in DB max_connections value of 100.  With the batch aggregate inserter on by default, the # of connections we require will be far less in 3.2.  With this setting back below max_connections for the DB, we should also avoid spurrious errors like:
org.hibernate.exception.GenericJDBCException: Cannot open connection 

[HHQ-1352]