Fixed class so that it doesn't exit the vm on shutdown. Cleaned up package deployment. This must also be run using the IsolatingDefaultSystemClassLoader, else we run into NoClassDefFoundErrors. Added proper exception handling for the threads started for isolating the default system classloader.